import type { RegistryEntry } from "../../shared.ts";
import { CURSOR_REGISTRY_VERSION, getCursorRegistryHeaders } from "../../shared.ts";

export const cursorProvider: RegistryEntry = {
  id: "cursor",
  alias: "cu",
  format: "cursor",
  executor: "cursor",
  baseUrl: "https://api2.cursor.sh",
  chatPath: "/aiserver.v1.ChatService/StreamUnifiedChatWithTools",
  authType: "oauth",
  authHeader: "bearer",
  defaultContextLength: 200000,
  headers: getCursorRegistryHeaders(),
  clientVersion: CURSOR_REGISTRY_VERSION,
  models: [
    { id: "auto", name: "Auto (current, default)" },
    { id: "auto-cost", name: "Auto (cost)" },
    { id: "auto-balance", name: "Auto (balance)" },
    { id: "auto-intelligence", name: "Auto (intelligence)" },
    // Legacy combo ids kept so existing cu/<id> targets are not orphaned.
    { id: "composer-2", name: "Composer 2" },
    { id: "composer-2-fast", name: "Composer 2 Fast" },
    { id: "gpt-5.4-low-fast", name: "GPT 5.4 Low Fast" },
    { id: "gpt-5.3-codex-spark-preview-low", name: "GPT 5.3 Codex Spark Preview Low" },
    { id: "gpt-5.3-codex-spark-preview", name: "GPT 5.3 Codex Spark Preview" },
    { id: "gpt-5.3-codex-spark-preview-high", name: "GPT 5.3 Codex Spark Preview High" },
    { id: "gpt-5.3-codex-spark-preview-xhigh", name: "GPT 5.3 Codex Spark Preview XHigh" },
    { id: "claude-4.6-opus-high-thinking-fast", name: "Claude 4.6 Opus High Thinking Fast" },
    { id: "claude-4.6-opus-max-thinking-fast", name: "Claude 4.6 Opus Max Thinking Fast" },
    { id: "claude-4.6-sonnet-medium", name: "Claude 4.6 Sonnet Medium" },
    { id: "claude-4.6-sonnet-medium-thinking", name: "Claude 4.6 Sonnet Medium Thinking" },
    { id: "gemini-3.1-pro", name: "Gemini 3.1 Pro" },
    { id: "gemini-3.7-flash", name: "Gemini 3.7 Flash" },
    { id: "gemini-3-flash", name: "Gemini 3 Flash" },
    { id: "grok-4.6-medium", name: "Grok 4.6 Medium" },
    { id: "grok-4.6-fast-medium", name: "Grok 4.6 Fast Medium" },
    { id: "grok-4.6-high", name: "Grok 4.6 High" },
    { id: "grok-4.6-fast-high", name: "Grok 4.6 Fast High" },
    { id: "grok-4.6-xhigh", name: "Grok 4.6 XHigh" },
    { id: "grok-4.6-fast-xhigh", name: "Grok 4.6 Fast XHigh" },
    { id: "kimi-k3", name: "Kimi K3" },
    { id: "kimi-k2.7-code", name: "Kimi K2.7 Code" },
    { id: "grok-4.3", name: "Grok 4.3" },
    { id: "grok-4.5-medium", name: "Grok 4.5 Medium" },
    { id: "grok-4.5-fast-medium", name: "Grok 4.5 Fast Medium" },
    { id: "grok-4.5-high", name: "Grok 4.5 High" },
    { id: "grok-4.5-fast-high", name: "Grok 4.5 Fast High" },
    { id: "grok-4.5-xhigh", name: "Grok 4.5 XHigh" },
    { id: "grok-4.5-fast-xhigh", name: "Grok 4.5 Fast XHigh" },
    { id: "kimi-k2.5", name: "Kimi K2.5" },
    { id: "gpt-5.3-codex-low", name: "Codex 5.3 Low" },
    { id: "gpt-5.3-codex-low-fast", name: "Codex 5.3 Low Fast" },
    { id: "gpt-5.3-codex", name: "Codex 5.3" },
    { id: "gpt-5.3-codex-fast", name: "Codex 5.3 Fast" },
    { id: "gpt-5.3-codex-high", name: "Codex 5.3 High" },
    { id: "gpt-5.3-codex-high-fast", name: "Codex 5.3 High Fast" },
    { id: "gpt-5.3-codex-xhigh", name: "Codex 5.3 Extra High" },
    { id: "gpt-5.3-codex-xhigh-fast", name: "Codex 5.3 Extra High Fast" },
    { id: "gpt-5.2", name: "GPT-5.2" },
    { id: "cursor-grok-4.5-high", name: "Cursor Grok 4.5" },
    { id: "cursor-grok-4.5-high-fast", name: "Cursor Grok 4.5 Fast" },
    { id: "composer-2.5", name: "Composer 2.5" },
    { id: "claude-opus-5-thinking-high", name: "Opus 5 1M Thinking" },
    { id: "claude-opus-5-thinking-high-fast", name: "Opus 5 1M Thinking Fast" },
    { id: "claude-opus-5-thinking-xhigh", name: "Opus 5 1M Extra High Thinking" },
    { id: "claude-opus-5-thinking-xhigh-fast", name: "Opus 5 1M Extra High Thinking Fast" },
    { id: "claude-opus-4-8-thinking-high", name: "Opus 4.8 1M Thinking" },
    { id: "claude-opus-4-8-thinking-high-fast", name: "Opus 4.8 1M Thinking Fast" },
    { id: "gpt-5.6-sol-high", name: "GPT-5.6 Sol 1M High" },
    { id: "gpt-5.6-sol-high-fast", name: "GPT-5.6 Sol High Fast" },
    { id: "gpt-5.6-sol-xhigh", name: "GPT-5.6 Sol 1M Extra High" },
    { id: "gpt-5.6-sol-xhigh-fast", name: "GPT-5.6 Sol Extra High Fast" },
    { id: "gpt-5.5-high", name: "GPT-5.5 1M High" },
    { id: "gpt-5.5-high-fast", name: "GPT-5.5 High Fast" },
    { id: "claude-fable-5-thinking-high", name: "Fable 5 1M Thinking (NO ZDR)" },
    { id: "claude-fable-5-thinking-xhigh", name: "Fable 5 1M Extra High Thinking (NO ZDR)" },
    { id: "claude-sonnet-5-thinking-high", name: "Sonnet 5 1M Thinking" },
    { id: "claude-sonnet-5-thinking-xhigh", name: "Sonnet 5 1M Extra High Thinking" },
    { id: "kimi-k3-high", name: "Kimi K3 High" },
    { id: "cursor-grok-4.5-low", name: "Cursor Grok 4.5 Low" },
    { id: "cursor-grok-4.5-low-fast", name: "Cursor Grok 4.5 Low Fast" },
    { id: "cursor-grok-4.5-medium", name: "Cursor Grok 4.5 Medium" },
    { id: "cursor-grok-4.5-medium-fast", name: "Cursor Grok 4.5 Medium Fast" },
    { id: "composer-2.5-fast", name: "Composer 2.5 Fast" },
    { id: "claude-opus-5-low", name: "Opus 5 1M Low" },
    { id: "claude-opus-5-low-fast", name: "Opus 5 1M Low Fast" },
    { id: "claude-opus-5-medium", name: "Opus 5 1M Medium" },
    { id: "claude-opus-5-medium-fast", name: "Opus 5 1M Medium Fast" },
    { id: "claude-opus-5-high", name: "Opus 5 1M" },
    { id: "claude-opus-5-high-fast", name: "Opus 5 1M Fast" },
    { id: "claude-opus-5-thinking-low", name: "Opus 5 1M Low Thinking" },
    { id: "claude-opus-5-thinking-low-fast", name: "Opus 5 1M Low Thinking Fast" },
    { id: "claude-opus-5-thinking-medium", name: "Opus 5 1M Medium Thinking" },
    { id: "claude-opus-5-thinking-medium-fast", name: "Opus 5 1M Medium Thinking Fast" },
    { id: "claude-opus-5-thinking-max", name: "Opus 5 1M Max Thinking" },
    { id: "claude-opus-5-thinking-max-fast", name: "Opus 5 1M Max Thinking Fast" },
    { id: "claude-opus-4-8-low", name: "Opus 4.8 1M Low" },
    { id: "claude-opus-4-8-low-fast", name: "Opus 4.8 1M Low Fast" },
    { id: "claude-opus-4-8-medium", name: "Opus 4.8 1M Medium" },
    { id: "claude-opus-4-8-medium-fast", name: "Opus 4.8 1M Medium Fast" },
    { id: "claude-opus-4-8-high", name: "Opus 4.8 1M" },
    { id: "claude-opus-4-8-high-fast", name: "Opus 4.8 1M Fast" },
    { id: "claude-opus-4-8-xhigh", name: "Opus 4.8 1M Extra High" },
    { id: "claude-opus-4-8-xhigh-fast", name: "Opus 4.8 1M Extra High Fast" },
    { id: "claude-opus-4-8-max", name: "Opus 4.8 1M Max" },
    { id: "claude-opus-4-8-max-fast", name: "Opus 4.8 1M Max Fast" },
    { id: "claude-opus-4-8-thinking-low", name: "Opus 4.8 1M Low Thinking" },
    { id: "claude-opus-4-8-thinking-low-fast", name: "Opus 4.8 1M Low Thinking Fast" },
    { id: "claude-opus-4-8-thinking-medium", name: "Opus 4.8 1M Medium Thinking" },
    { id: "claude-opus-4-8-thinking-medium-fast", name: "Opus 4.8 1M Medium Thinking Fast" },
    { id: "claude-opus-4-8-thinking-xhigh", name: "Opus 4.8 1M Extra High Thinking" },
    { id: "claude-opus-4-8-thinking-xhigh-fast", name: "Opus 4.8 1M Extra High Thinking Fast" },
    { id: "claude-opus-4-8-thinking-max", name: "Opus 4.8 1M Max Thinking" },
    { id: "claude-opus-4-8-thinking-max-fast", name: "Opus 4.8 1M Max Thinking Fast" },
    { id: "gpt-5.6-sol-none", name: "GPT-5.6 Sol 1M None" },
    { id: "gpt-5.6-sol-none-fast", name: "GPT-5.6 Sol None Fast" },
    { id: "gpt-5.6-sol-low", name: "GPT-5.6 Sol 1M Low" },
    { id: "gpt-5.6-sol-low-fast", name: "GPT-5.6 Sol Low Fast" },
    { id: "gpt-5.6-sol-medium", name: "GPT-5.6 Sol 1M" },
    { id: "gpt-5.6-sol-medium-fast", name: "GPT-5.6 Sol Fast" },
    { id: "gpt-5.6-sol-max", name: "GPT-5.6 Sol 1M Max" },
    { id: "gpt-5.6-sol-max-fast", name: "GPT-5.6 Sol Max Fast" },
    { id: "gpt-5.5-none", name: "GPT-5.5 1M None" },
    { id: "gpt-5.5-none-fast", name: "GPT-5.5 None Fast" },
    { id: "gpt-5.5-low", name: "GPT-5.5 1M Low" },
    { id: "gpt-5.5-low-fast", name: "GPT-5.5 Low Fast" },
    { id: "gpt-5.5-medium", name: "GPT-5.5 1M" },
    { id: "gpt-5.5-medium-fast", name: "GPT-5.5 Fast" },
    { id: "gpt-5.5-extra-high", name: "GPT-5.5 1M Extra High" },
    { id: "gpt-5.5-extra-high-fast", name: "GPT-5.5 Extra High Fast" },
    { id: "claude-fable-5-low", name: "Fable 5 1M Low (NO ZDR)" },
    { id: "claude-fable-5-medium", name: "Fable 5 1M Medium (NO ZDR)" },
    { id: "claude-fable-5-high", name: "Fable 5 1M (NO ZDR)" },
    { id: "claude-fable-5-xhigh", name: "Fable 5 1M Extra High (NO ZDR)" },
    { id: "claude-fable-5-max", name: "Fable 5 1M Max (NO ZDR)" },
    { id: "claude-fable-5-thinking-low", name: "Fable 5 1M Low Thinking (NO ZDR)" },
    { id: "claude-fable-5-thinking-medium", name: "Fable 5 1M Medium Thinking (NO ZDR)" },
    { id: "claude-fable-5-thinking-max", name: "Fable 5 1M Max Thinking (NO ZDR)" },
    { id: "claude-sonnet-5-low", name: "Sonnet 5 1M Low" },
    { id: "claude-sonnet-5-medium", name: "Sonnet 5 1M Medium" },
    { id: "claude-sonnet-5-high", name: "Sonnet 5 1M" },
    { id: "claude-sonnet-5-xhigh", name: "Sonnet 5 1M Extra High" },
    { id: "claude-sonnet-5-max", name: "Sonnet 5 1M Max" },
    { id: "claude-sonnet-5-thinking-low", name: "Sonnet 5 1M Low Thinking" },
    { id: "claude-sonnet-5-thinking-medium", name: "Sonnet 5 1M Medium Thinking" },
    { id: "claude-sonnet-5-thinking-max", name: "Sonnet 5 1M Max Thinking" },
    { id: "gpt-5.6-terra-none", name: "GPT-5.6 Terra 1M None" },
    { id: "gpt-5.6-terra-none-fast", name: "GPT-5.6 Terra None Fast" },
    { id: "gpt-5.6-terra-low", name: "GPT-5.6 Terra 1M Low" },
    { id: "gpt-5.6-terra-low-fast", name: "GPT-5.6 Terra Low Fast" },
    { id: "gpt-5.6-terra-medium", name: "GPT-5.6 Terra 1M" },
    { id: "gpt-5.6-terra-medium-fast", name: "GPT-5.6 Terra Fast" },
    { id: "gpt-5.6-terra-high", name: "GPT-5.6 Terra 1M High" },
    { id: "gpt-5.6-terra-high-fast", name: "GPT-5.6 Terra High Fast" },
    { id: "gpt-5.6-terra-xhigh", name: "GPT-5.6 Terra 1M Extra High" },
    { id: "gpt-5.6-terra-xhigh-fast", name: "GPT-5.6 Terra Extra High Fast" },
    { id: "gpt-5.6-terra-max", name: "GPT-5.6 Terra 1M Max" },
    { id: "gpt-5.6-terra-max-fast", name: "GPT-5.6 Terra Max Fast" },
    { id: "claude-opus-4-7-low", name: "Opus 4.7 1M Low" },
    { id: "claude-opus-4-7-low-fast", name: "Opus 4.7 1M Low Fast" },
    { id: "claude-opus-4-7-medium", name: "Opus 4.7 1M Medium" },
    { id: "claude-opus-4-7-medium-fast", name: "Opus 4.7 1M Medium Fast" },
    { id: "claude-opus-4-7-high", name: "Opus 4.7 1M High" },
    { id: "claude-opus-4-7-high-fast", name: "Opus 4.7 1M High Fast" },
    { id: "claude-opus-4-7-xhigh", name: "Opus 4.7 1M" },
    { id: "claude-opus-4-7-xhigh-fast", name: "Opus 4.7 1M Fast" },
    { id: "claude-opus-4-7-max", name: "Opus 4.7 1M Max" },
    { id: "claude-opus-4-7-max-fast", name: "Opus 4.7 1M Max Fast" },
    { id: "claude-opus-4-7-thinking-low", name: "Opus 4.7 1M Low Thinking" },
    { id: "claude-opus-4-7-thinking-low-fast", name: "Opus 4.7 1M Low Thinking Fast" },
    { id: "claude-opus-4-7-thinking-medium", name: "Opus 4.7 1M Medium Thinking" },
    { id: "claude-opus-4-7-thinking-medium-fast", name: "Opus 4.7 1M Medium Thinking Fast" },
    { id: "claude-opus-4-7-thinking-high", name: "Opus 4.7 1M High Thinking" },
    { id: "claude-opus-4-7-thinking-high-fast", name: "Opus 4.7 1M High Thinking Fast" },
    { id: "claude-opus-4-7-thinking-xhigh", name: "Opus 4.7 1M Thinking" },
    { id: "claude-opus-4-7-thinking-xhigh-fast", name: "Opus 4.7 1M Thinking Fast" },
    { id: "claude-opus-4-7-thinking-max", name: "Opus 4.7 1M Max Thinking" },
    { id: "claude-opus-4-7-thinking-max-fast", name: "Opus 4.7 1M Max Thinking Fast" },
    { id: "gpt-5.4-low", name: "GPT-5.4 1M Low" },
    { id: "gpt-5.4-medium", name: "GPT-5.4 1M" },
    { id: "gpt-5.4-medium-fast", name: "GPT-5.4 Fast" },
    { id: "gpt-5.4-high", name: "GPT-5.4 1M High" },
    { id: "gpt-5.4-high-fast", name: "GPT-5.4 High Fast" },
    { id: "gpt-5.4-xhigh", name: "GPT-5.4 1M Extra High" },
    { id: "gpt-5.4-xhigh-fast", name: "GPT-5.4 Extra High Fast" },
    { id: "claude-4.6-opus-high", name: "Opus 4.6 1M" },
    { id: "claude-4.6-opus-max", name: "Opus 4.6 1M Max" },
    { id: "claude-4.6-opus-high-thinking", name: "Opus 4.6 1M Thinking" },
    { id: "claude-4.6-opus-max-thinking", name: "Opus 4.6 1M Max Thinking" },
    { id: "claude-4.5-opus-high", name: "Opus 4.5" },
    { id: "claude-4.5-opus-high-thinking", name: "Opus 4.5 Thinking" },
    { id: "gpt-5.2-low", name: "GPT-5.2 Low" },
    { id: "gpt-5.2-low-fast", name: "GPT-5.2 Low Fast" },
    { id: "gpt-5.2-fast", name: "GPT-5.2 Fast" },
    { id: "gpt-5.2-high", name: "GPT-5.2 High" },
    { id: "gpt-5.2-high-fast", name: "GPT-5.2 High Fast" },
    { id: "gpt-5.2-xhigh", name: "GPT-5.2 Extra High" },
    { id: "gpt-5.2-xhigh-fast", name: "GPT-5.2 Extra High Fast" },
    { id: "gpt-5.6-luna-none", name: "GPT-5.6 Luna 1M None" },
    { id: "gpt-5.6-luna-none-fast", name: "GPT-5.6 Luna None Fast" },
    { id: "gpt-5.6-luna-low", name: "GPT-5.6 Luna 1M Low" },
    { id: "gpt-5.6-luna-low-fast", name: "GPT-5.6 Luna Low Fast" },
    { id: "gpt-5.6-luna-medium", name: "GPT-5.6 Luna 1M" },
    { id: "gpt-5.6-luna-medium-fast", name: "GPT-5.6 Luna Fast" },
    { id: "gpt-5.6-luna-high", name: "GPT-5.6 Luna 1M High" },
    { id: "gpt-5.6-luna-high-fast", name: "GPT-5.6 Luna High Fast" },
    { id: "gpt-5.6-luna-xhigh", name: "GPT-5.6 Luna 1M Extra High" },
    { id: "gpt-5.6-luna-xhigh-fast", name: "GPT-5.6 Luna Extra High Fast" },
    { id: "gpt-5.6-luna-max", name: "GPT-5.6 Luna 1M Max" },
    { id: "gpt-5.6-luna-max-fast", name: "GPT-5.6 Luna Max Fast" },
    { id: "gemini-3.6-flash-minimal", name: "Gemini 3.6 Flash Minimal" },
    { id: "gemini-3.6-flash-low", name: "Gemini 3.6 Flash Low" },
    { id: "gemini-3.6-flash-medium", name: "Gemini 3.6 Flash Medium" },
    { id: "gemini-3.6-flash-high", name: "Gemini 3.6 Flash" },
    { id: "gpt-5.4-mini-none", name: "GPT-5.4 Mini None" },
    { id: "gpt-5.4-mini-low", name: "GPT-5.4 Mini Low" },
    { id: "gpt-5.4-mini-medium", name: "GPT-5.4 Mini" },
    { id: "gpt-5.4-mini-high", name: "GPT-5.4 Mini High" },
    { id: "gpt-5.4-mini-xhigh", name: "GPT-5.4 Mini Extra High" },
    { id: "gpt-5.4-nano-none", name: "GPT-5.4 Nano None" },
    { id: "gpt-5.4-nano-low", name: "GPT-5.4 Nano Low" },
    { id: "gpt-5.4-nano-medium", name: "GPT-5.4 Nano" },
    { id: "gpt-5.4-nano-high", name: "GPT-5.4 Nano High" },
    { id: "gpt-5.4-nano-xhigh", name: "GPT-5.4 Nano Extra High" },
    { id: "claude-4.5-sonnet", name: "Sonnet 4.5" },
    { id: "claude-4.5-sonnet-thinking", name: "Sonnet 4.5 Thinking" },
    { id: "gpt-5.1-low", name: "GPT-5.1 Low" },
    { id: "gpt-5.1", name: "GPT-5.1" },
    { id: "gpt-5.1-high", name: "GPT-5.1 High" },
    { id: "claude-4-sonnet", name: "Sonnet 4" },
    { id: "claude-4-sonnet-thinking", name: "Sonnet 4 Thinking" },
    { id: "gpt-5-mini", name: "GPT-5 Mini" },
    { id: "kimi-k3-low", name: "Kimi K3 Low" },
    { id: "kimi-k3-max", name: "Kimi K3" },
    { id: "glm-5.2-high", name: "GLM 5.2" },
    { id: "glm-5.2-max", name: "GLM 5.2 Max" },
  ],
};

/**
 * API-key variant of the Cursor provider.
 *
 * Same wire protocol, executor and catalog as `cursor`, but the connection
 * holds a Cursor user API key (`crsr_…`, cursor.com/dashboard/api) instead of
 * an IDE/OAuth session. The executor exchanges that key for a session token
 * on demand (open-sse/services/cursorApiKeyAuth.ts), so no cursor-agent or
 * IDE install is needed on the OmniRoute host. Kept as a distinct backend ID
 * so API-key and IDE-session connections never share renewal, quota or
 * dashboard semantics.
 */
export const cursor_apiProvider: RegistryEntry = {
  id: "cursor-api",
  alias: "cua",
  format: cursorProvider.format,
  executor: "cursor-api",
  baseUrl: cursorProvider.baseUrl,
  chatPath: cursorProvider.chatPath,
  authType: "apikey",
  authHeader: "bearer",
  defaultContextLength: cursorProvider.defaultContextLength,
  headers: getCursorRegistryHeaders(),
  clientVersion: CURSOR_REGISTRY_VERSION,
  models: cursorProvider.models,
};
