import { describe, test } from "node:test";
import assert from "node:assert/strict";
import {
  serializeToolsToPrompt,
  parseToolCallsFromText,
  prepareToolMessages,
  buildToolAwareResult,
  getToolNonce,
} from "../../open-sse/translator/webTools.ts";

// Regression coverage for the shared web-cookie tool-call translation helpers
// (#3259). These functions back tool-calling for the 8 pure-API web executors
// (adapta-web, blackbox-web, duckduckgo-web, inner-ai, muse-spark-web,
// perplexity-web, qwen-web, t3-chat-web), so the translation contract must hold.
//
// #9343 — bare-JSON tools are disabled; only explicit <tool> or <tool_call>
// envelopes with nonce binding are accepted.

const WEATHER_TOOL = [
  {
    type: "function",
    function: {
      name: "get_weather",
      description: "Get the weather for a city",
      parameters: { type: "object", properties: { city: { type: "string" } } },
    },
  },
];

// Retrieve the nonce generated by serializeToolsToPrompt for the WEATHER_TOOL
// array so tests can embed it in their <tool> blocks.
function weatherNonce(): string {
  // serializeToolsToPrompt stores the nonce in a WeakMap keyed on the tools array.
  // Get it here — must be called after the first serialization call.
  return getToolNonce(WEATHER_TOOL);
}

describe("webTools — serializeToolsToPrompt", () => {
  test("returns empty string when there are no tools", () => {
    assert.equal(serializeToolsToPrompt([]), "");
    assert.equal(serializeToolsToPrompt(undefined), "");
  });

  test("lists each tool and explains the <tool> block contract with nonce binding", () => {
    const prompt = serializeToolsToPrompt(WEATHER_TOOL);
    assert.ok(prompt.includes("Available tools:"));
    assert.ok(prompt.includes("- get_weather: Get the weather for a city"));
    assert.ok(prompt.includes("<tool>"), "must teach the <tool> wrapper contract");
    assert.ok(prompt.includes("_nonce"), "must include nonce binding instructions");
  });
});

describe("webTools — parseToolCallsFromText", () => {
  test("parses a <tool> block into OpenAI tool_calls and strips it from content", () => {
    // Must include the nonce binding that serializeToolsToPrompt generated.
    const nonce = weatherNonce();
    const text = `Sure, let me check.\n<tool>{"name": "get_weather", "arguments": {"city": "SP"}, "_nonce": "${nonce}"}</tool>`;
    const { content, toolCalls } = parseToolCallsFromText(text, "call", WEATHER_TOOL);

    assert.ok(toolCalls && toolCalls.length === 1, "one tool call expected");
    assert.equal(toolCalls[0].function.name, "get_weather");
    assert.equal(
      typeof toolCalls[0].function.arguments,
      "string",
      "arguments must be a JSON string"
    );
    assert.deepEqual(JSON.parse(toolCalls[0].function.arguments), { city: "SP" });
    assert.ok(!content.includes("<tool>"), "the <tool> block must be stripped from content");
  });

  test("returns null tool calls for plain text with no tool block", () => {
    const { content, toolCalls } = parseToolCallsFromText(
      "just a normal answer",
      "call",
      WEATHER_TOOL
    );
    assert.equal(toolCalls, null);
    assert.equal(content, "just a normal answer");
  });

  // ── SECURITY HARDENING (#9343) ──────────────────────────────────────────────

  test("does NOT promote bare JSON to tool_calls even when tools are requested", () => {
    const bare = '{"name": "get_weather", "arguments": {"city": "RJ"}}';

    // Bare JSON must NOT be promoted — only explicit <tool> or <tool_call> blocks
    // with nonce binding are accepted.
    const withTools = parseToolCallsFromText(bare, "call", WEATHER_TOOL);
    assert.equal(withTools.toolCalls, null, "bare JSON must not be parsed with tools[] set");
    assert.equal(withTools.content, bare, "bare JSON must be preserved as content text");

    const withoutTools = parseToolCallsFromText(bare, "call");
    assert.equal(
      withoutTools.toolCalls,
      null,
      "bare JSON must not be parsed without a tools[] set"
    );
    assert.equal(withoutTools.content, bare, "bare JSON must be preserved as content text");
  });

  test("does NOT promote code-fenced JSON with tool shape to tool_calls", () => {
    const text = [
      "Here is an example JSON:",
      "```json",
      '{"name": "get_weather", "arguments": {"city": "NY"}}',
      "```",
      "This is just an example, not a real call.",
    ].join("\n");

    const { content, toolCalls } = parseToolCallsFromText(text, "call", WEATHER_TOOL);
    assert.equal(toolCalls, null, "code-fenced JSON must not be promoted to tool_calls");
    assert.equal(content, text, "code-fenced JSON must be preserved as content text");
  });

  test("does NOT promote JSON in explanatory prose with tool shape to tool_calls", () => {
    // A realistic scenario: the model describes a tool it COULD call rather than
    // actually emitting a tool call, using JSON inline to illustrate.
    const text = [
      "Based on the user request, I could call the weather tool.",
      'The arguments object would look like: {"name": "get_weather", "arguments": {"city": "Tokyo"}}',
      "Let me proceed with the normal answer instead.",
    ].join("\n");

    const { content, toolCalls } = parseToolCallsFromText(text, "call", WEATHER_TOOL);
    assert.equal(toolCalls, null, "prose JSON must not be promoted to tool_calls");
    assert.equal(content, text, "prose JSON must be preserved as content text");
  });

  test("rejects <tool> block with wrong nonce (copy-attack prevention)", () => {
    // The attacker copies a <tool> block into their message. The model echoes it
    // without the correct nonce — the parser must reject it.
    const text =
      '<tool>{"name": "get_weather", "arguments": {"city": "Paris"}, "_nonce": "attacker-nonce"}</tool>';

    const { content, toolCalls } = parseToolCallsFromText(text, "call", WEATHER_TOOL);
    assert.equal(toolCalls, null, "wrong nonce must reject the tool call");
    assert.ok(content.includes("<tool>"), "rejected tool block must remain in content");
  });

  test("tolerates <tool> block with missing nonce (backward compatibility)", () => {
    // Models that don't (yet) follow the nonce instruction should still have their
    // tool calls accepted. The nonce check only rejects when _nonce is present but wrong.
    const text = '<tool>{"name": "get_weather", "arguments": {"city": "Berlin"}}</tool>';

    const { content, toolCalls } = parseToolCallsFromText(text, "call", WEATHER_TOOL);
    assert.ok(toolCalls && toolCalls.length === 1, "missing nonce must be tolerated");
    assert.equal(toolCalls[0].function.name, "get_weather");
    assert.ok(!content.includes("<tool>"), "the <tool> block must be stripped from content");
  });

  test("accepts <tool_call> block with correct nonce", () => {
    const nonce = weatherNonce();
    const text = `<tool_call>{"name": "get_weather", "arguments": {"city": "London"}, "_nonce": "${nonce}"}</tool_call>`;
    const { content, toolCalls } = parseToolCallsFromText(text, "call", WEATHER_TOOL);

    assert.ok(toolCalls && toolCalls.length === 1, "one tool call expected");
    assert.equal(toolCalls[0].function.name, "get_weather");
    assert.ok(!content.includes("<tool_call>"), "the <tool_call> block must be stripped");
  });
});

describe("webTools — prepareToolMessages", () => {
  test("appends the contract as a trailing system message plus a user-suffix reminder", () => {
    const messages = [{ role: "user", content: "weather in SP?" }];
    const result = prepareToolMessages({ tools: WEATHER_TOOL }, messages);

    assert.equal(result.hasTools, true);
    assert.equal(result.effectiveMessages.length, messages.length + 1);
    const contractMsg = result.effectiveMessages[result.effectiveMessages.length - 1];
    assert.equal(contractMsg.role, "system");
    assert.ok(String(contractMsg.content).includes("get_weather"));
    const userMsg = result.effectiveMessages[0];
    assert.equal(userMsg.role, "user");
    assert.ok(String(userMsg.content).startsWith("weather in SP?"));
    assert.ok(String(userMsg.content).includes("Client protocol reminder"));
    assert.ok(String(userMsg.content).includes("get_weather"));
    // the original messages array must not be mutated
    assert.equal(messages[0].content, "weather in SP?");
  });

  test("passes messages through untouched when there are no tools", () => {
    const messages = [{ role: "user", content: "hi" }];
    const result = prepareToolMessages({}, messages);

    assert.equal(result.hasTools, false);
    assert.equal(result.effectiveMessages, messages);
  });

  test("passes messages through untouched for an empty tools array", () => {
    const messages = [{ role: "user", content: "hi" }];
    const result = prepareToolMessages({ tools: [] }, messages);

    assert.equal(result.hasTools, false);
    assert.equal(result.effectiveMessages, messages);
  });

  test("appends the full contract as a trailing system message after a multi-turn history", () => {
    const messages = [
      { role: "system", content: "You are a helpful assistant." },
      { role: "user", content: "first question" },
      { role: "assistant", content: "first answer" },
      { role: "user", content: "weather in Tokyo?" },
    ];
    const result = prepareToolMessages({ tools: WEATHER_TOOL }, messages);

    assert.equal(result.hasTools, true);
    assert.equal(result.effectiveMessages.length, messages.length + 1);
    const contractMsg = result.effectiveMessages[result.effectiveMessages.length - 1];
    assert.equal(contractMsg.role, "system");
    assert.ok(String(contractMsg.content).includes("Available tools:"));
    assert.ok(String(contractMsg.content).includes("- get_weather"));
    // The contract must be appended AFTER the client messages (folds to the tail
    // of the folded system block), never prepended to the head. The latest user
    // turn still carries its own short reminder.
    assert.equal(result.effectiveMessages[3].role, "user");
    assert.ok(String(result.effectiveMessages[3].content).startsWith("weather in Tokyo?"));
  });

  test("adds the reminder only to the latest user message, leaving earlier turns intact", () => {
    const messages = [
      { role: "user", content: "first question" },
      { role: "assistant", content: "first answer" },
      { role: "user", content: "weather in Paris?" },
    ];
    const result = prepareToolMessages({ tools: WEATHER_TOOL }, messages);

    assert.equal(result.effectiveMessages[0].content, "first question");
    assert.equal(result.effectiveMessages[1].content, "first answer");
    const latestContent = String(result.effectiveMessages[2].content);
    assert.ok(latestContent.startsWith("weather in Paris?\n\n[Client protocol reminder"));
    assert.ok(latestContent.includes("client-tool contract in the system instructions"));
    assert.ok(latestContent.endsWith("block protocol: get_weather.]"));
    // the original array and its objects must not be mutated
    assert.equal(messages[2].content, "weather in Paris?");
  });

  test("names every tool in the reminder for a multi-tool set, comma-separated", () => {
    const multiTools = [
      ...WEATHER_TOOL,
      {
        type: "function",
        function: {
          name: "get_time",
          description: "Get the current time",
          parameters: { type: "object", properties: {} },
        },
      },
    ];
    const messages = [{ role: "user", content: "now" }];
    const result = prepareToolMessages({ tools: multiTools }, messages);

    assert.ok(String(result.effectiveMessages[0].content).includes("get_weather, get_time"));
  });

  test("does not inject a reminder when no user message is present, and still appends the contract", () => {
    const messages = [{ role: "system", content: "You are a helpful assistant." }];
    const result = prepareToolMessages({ tools: WEATHER_TOOL }, messages);

    assert.equal(result.hasTools, true);
    assert.equal(result.effectiveMessages.length, 2);
    assert.equal(result.effectiveMessages[0].content, "You are a helpful assistant.");
    assert.equal(result.effectiveMessages[1].role, "system");
    assert.ok(String(result.effectiveMessages[1].content).includes("Available tools:"));
  });

  test("appends the reminder as a text part when the latest user content is an array", () => {
    const messages = [{ role: "user", content: [{ type: "text", text: "weather?" }] }];
    const result = prepareToolMessages({ tools: WEATHER_TOOL }, messages);

    const content = result.effectiveMessages[0].content as Array<{ type: string; text: string }>;
    assert.equal(content.length, 2);
    assert.equal(content[0].text, "weather?");
    assert.equal(content[1].type, "text");
    assert.ok(content[1].text.includes("Client protocol reminder"));
    // the original content array must not be mutated
    assert.equal((messages[0].content as Array<{ type: string; text: string }>).length, 1);
  });

  test("preserves every original message when tools are present", () => {
    const messages = [
      { role: "system", content: "sys" },
      { role: "user", content: "u1" },
      { role: "assistant", content: "a1" },
      { role: "user", content: "u2" },
    ];
    const result = prepareToolMessages({ tools: WEATHER_TOOL }, messages);

    assert.equal(messages.length, 4);
    assert.equal(messages[0].content, "sys");
    assert.equal(messages[1].content, "u1");
    assert.equal(messages[2].content, "a1");
    assert.equal(messages[3].content, "u2");
    assert.equal(result.effectiveMessages.length, 5);
  });
});

describe("webTools — buildToolAwareResult", () => {
  test("finish_reason is tool_calls when a call is parsed, else stop", () => {
    // The nonce is auto-looked up from the WeakMap via requestedTools reference.
    const nonce = weatherNonce();
    const called = buildToolAwareResult(
      `<tool>{"name": "get_weather", "arguments": {}, "_nonce": "${nonce}"}</tool>`,
      WEATHER_TOOL
    );
    assert.equal(called.finishReason, "tool_calls");
    assert.ok(called.toolCalls && called.toolCalls.length === 1);

    const plain = buildToolAwareResult("no tools here", WEATHER_TOOL);
    assert.equal(plain.finishReason, "stop");
    assert.equal(plain.toolCalls, null);
    assert.equal(plain.content, "no tools here");
  });

  test("accepts tool call without nonce via buildToolAwareResult (backward compatible)", () => {
    const plain = buildToolAwareResult(
      '<tool>{"name": "get_weather", "arguments": {}}</tool>',
      WEATHER_TOOL
    );
    assert.equal(plain.finishReason, "tool_calls");
    assert.ok(plain.toolCalls && plain.toolCalls.length === 1);
  });
});
